### ISSUE TITLE
Tracking Issue for MPL-2.0 Conversion 

### ISSUE THREAD

**Issue by cwfitzgerald** [NovaMods/nova-rs#41]
We wish to relicense nova-rs from its current license (MIT) to the MPL-2.0. All contributors must give the okay as a comment to this issue.

Contributors:
@DethRaid 
@cwfitzgerald 
@Janrupf 
@fridtjof 

Just copy paste the following:

I approve of my code in nova-rs frying licensed under the MPL-2.0.

**Comment by cwfitzgerald** [comment]
I approve of my code in nova-rs frying licensed under the MPL-2.0.

**Comment by fridtjof** [comment]
I approve of my code in nova-rs frying licensed under the MPL-2.0.

**Comment by DethRaid** [comment]
I approve of my code in nova-rs frying licensed under the MPL-2.0.

**Comment by Janrupf** [comment]
I approve of my code in nova-rs frying licensed under the MPL-2.0.
